version: '2.0'
services:
  mongo:
    image: mongo:3
    volumes:
      - 'mongo_data:/data/db'
      - '.:/backup'
    ports:
      - '27017:27017'
  python:
    build:
      context: .
    volumes:
      - '.:/data'
    working_dir: '/data'
    command:  tail -F anything
    depends_on:
      - mongo
    links:
      - mongo
volumes:
  mongo_data: null
