version: 2
jobs:
  build-python27:
    working_directory: ~/data
    docker:
      - image: circleci/python:2.7
    steps:
      - run:
          command: |
            sudo pip install py2venv
      - checkout
      - restore_cache:
          key: deps-27-{{ .Branch }}-{{ checksum "requirements.txt" }}{{ checksum "requirements_dev.txt" }}
      - run:
          name: 'pip install'
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements_dev.txt
      - save_cache:
          key: deps-27-{{ .Branch }}-{{ checksum "requirements.txt" }}{{ checksum "requirements_dev.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            make install lint test coverage docs
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
  build-python36:
    working_directory: ~/data
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - restore_cache:
          key: deps-36-{{ .Branch }}-{{ checksum "requirements.txt" }}{{ checksum "requirements_dev.txt" }}
      - run:
          name: 'pip install'
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements_dev.txt
      - save_cache:
          key: deps-36-{{ .Branch }}-{{ checksum "requirements.txt" }}{{ checksum "requirements_dev.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            make install lint test coverage docs
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/


workflows:
  version: 2
  build:
    jobs:
      - build-python27
      - build-python36
