name: python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # caching pip dependencies-
      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt
          pip install -e .
      - name: lint
        run: invoke lint
      - name: format
        run: invoke format --check
      - name: mypy
        run: invoke mypy
      - name: test
        run: invoke test
